### ISSUE TITLE
How to use it is it work in window

### ISSUE THREAD

**Issue by mzubairtalha** [arma7x/kaios-sendevent#1]
How to use it is it work in window

**Comment by arma7x** [comment]
https://stackoverflow.com/questions/6413377/is-there-a-way-to-run-bash-scripts-on-windows

Read this http://adbcommand.com/articles/adb%20shell%EF%BC%9Agetevent%20and%20sendevent to extract list of your device's keypad events

https://source.android.com/docs/core/interaction/input/getevent
